### ISSUE TITLE
unable to modify string

### ISSUE THREAD

**Issue by ethers** [ethereum/serpent#37]
```
def f2(string:s):
    setch(string, 0, "a")
    setch(string, 1, "b")

def t2():
    string = text("cd")
    self.f2(string)
    return([getch(string,0), getch(string,1)]:a)  # should return [97,98]
```

when calling t2()
actual: [99,100]
expected: [97,98]

**Comment by vbuterin** [comment]
No, it's fine as-is. The problem is that when you call f2, the copy of "string" initialized inside t2 becomes immutable. It's in the memory instantiated by t2, so it's not accessible by f2 except as a calldata argument which can be read.
