### ISSUE TITLE
modifying array in another function

### ISSUE THREAD

**Issue by ethers** [ethereum/serpent#38]
```
def f2(arr:a):
    arr[0] = 1
    arr[1] = 2

def t2():
    a = array(2)
    a[0] = 3
    a[1] = 4
    self.f2(a)
    return(a:a)
```

when calling t2()
actual: [3,4]
expected: [1,2]

**Comment by vbuterin** [comment]
That's not a bug. Arrays do not persist through calls like that. You want:

def f2(arr:a)
    a[0] = 1
    a[1] = 2
    return(a:a)

def t2():
    a = array(2)
    a[0] = 3
    a[1] = 4
    a = self.f2(a, outsz=2)
    return(a:a)

**Comment by ethers** [comment]
as suggested, I've been using outsz and looks good

**Comment by ethers** [comment]
for f2() I think you meant this:

```
def f2(arr:a):
    arr[0] = 1
    arr[1] = 2
    return(arr:a)

def t2():
    a = array(2)
    a[0] = 3
    a[1] = 4
    self.f2(a, outsz=2)
    return(a:a)
```

but this still returns [3,4] instead of [1,2]
