### ISSUE TITLE
global variable scoping/modifying

### ISSUE THREAD

**Issue by ethers** [ethereum/serpent#41]
see inline comment in code below:

```
data pos
self.pos=0


def readVarintNum():
    log(self.pos)  # shouldn't self.pos be 4 here ?  or how can I update self.pos from readUInt32LE() ?

def readUInt32LE():
    self.pos += 4

def run():
    self.pos = 0
    self.readUInt32LE()
    log(self.pos)
    ins = self.readVarintNum()
```

**Comment by ethers** [comment]
commenting out line#2 (the assignment after data pos) leads to desired behavior.
but keeping this issue open since it still appears to be a bug

**Comment by vbuterin** [comment]
Your problem is that self.pos=0 runs every time the contract is run. You want to put that inside an init function.

**Comment by ethers** [comment]
Thanks
