### ISSUE TITLE
inset at top of file doesn't work

### ISSUE THREAD

**Issue by ethers** [ethereum/serpent#44]
```
inset('bar.py')

# this is what's in bar.py
# def g(n):
#     return(n+10)
#
# def f(n):
#     return(n*2)


def foo():
    res = self.g(12)

    return(res)
```

On my machine, the return value is always [10], regardless of which function is called.

Moving inset() to the bottom of the file is a workaround.

**Comment by vbuterin** [comment]
Fixed:

https://github.com/ethereum/pyethereum/commit/e03f67b69249cb9ee4d2c1c5ce5c239e4f1aedf5
