### ISSUE TITLE
Calling any extern method keeps asking to use the "as" keyword

### ISSUE THREAD

**Issue by caktux** [ethereum/serpent#46]
Even if the "as" keyword is already being used, serpent ignores the extern definition and returns "_" as signature, yielding the `Method x has multiple definitions. Please use the "as" keyword...` error

**Comment by vbuterin** [comment]
Can I see a minimal failing testcase?

**Comment by caktux** [comment]
Just run pyethereum tests, any contract test using extern fails that way.

**Comment by vbuterin** [comment]
The "as" keyword is now deprecated; the only way of resolving ambiguities is now to use the function::sig(...) syntax. In all cases where as was not used, the programs should now either be valid or the compiler will point out the ambiguity to you.
