### ISSUE TITLE
global string value is lost

### ISSUE THREAD

**Issue by ethers** [ethereum/serpent#47]
the log in foo() shows correct, but the log in g() is empty... ?

```
data buf

def foo():
    mystr = text("01ab")
    self.buf = mystr
    log(datastr=self.buf)
    self.g()

def g():
    log(datastr=self.buf)  # this logs empty
```

**Comment by vbuterin** [comment]
Yeah, the issue is that mystr is an object in memory, and so doing self.buf = mystr only stores the index into storage, not the actual string.
