### ISSUE TITLE
return([1,2,3], items=3) # No array returned latest devel commit

### ISSUE THREAD

**Issue by Georgi87** [ethereum/serpent#51]
Hi, thanks for your great work Vitalik. I am using serpent for some exchange contracts. I encountered the problem that functions don't return arrays but integers. I am working on the latest develop commit. 

def return_array():
......return([1,2,3], items=3)

def main():
.....log(self.return_array())  # logs ('LOG', 'c305c901078781c232a2a521c2af7980f8385ee9', [1L], [])

**Comment by vbuterin** [comment]
You wrote the code wrong. See https://github.com/ethereum/pyethereum/blob/develop/tests/test_contracts.py#L705

**Comment by Georgi87** [comment]
Thank you. My bad. All works now:

def return_array():
......return([1,2,3], items=3)

def main():
.....dataarr = self.return_array(outitems=3)
