### ISSUE TITLE
Compiled serpent code with insets doesn't work in js abi

### ISSUE THREAD

**Issue by joeykrug** [ethereum/serpent#57]
When I use the JS API to connect to alethzero I can publish a compiled hex serpent contract without insets and a simple function call like double(2) will return 4. If I have an inset, even if the inset doesn't do anything, it returns 0

**Comment by jorisbontje** [comment]
Can you share your code?

**Comment by joeykrug** [comment]
Sure --- here's a simple test case that fails.  I think I've narrowed the issue down to macros with with.  If I remove the macro (even though it does nothing in this since I don't call it, I can call faucet and it returns something other than 0).

#   var evm = '0x...';
#   var address = web3.eth.transact({code: evm});
#   serpent mk_full_signature and set desc to output
#   var contract = web3.eth.contract(address, desc);

data cashcoinBalances[]

def init():
    # test initial funds
    self.cashcoinBalances[tx.origin] = 1000000*2^64

def faucet():
    sender = tx.origin
    self.cashcoinBalances[sender] = 10000*2^64
    return(10000*2^64)

# Proportional distance from zero, inputs are fixed point
macro get_weight($a, $asz):
    with total = 0:
        with i = 0:
            while i < $asz:
                $a[i] = abs($a[i])
                total += $a[i]
                i += 1
        with wt = array($asz):
            with i = 0:
                while i < $asz:
                    wt[i] = $a[i] * 2^64 / total
                    i += 1
            wt

**Comment by vbuterin** [comment]
I don't understand what the failure is. The way you set up def faucet(), it returns 100002 ^ 64, which is a really big number.

Also, if you paste code, can you try to either link to a text file or format it as code, so that the whitespaces do not disappear?

**Comment by joeykrug** [comment]
I forgot to add backticks, added.  Faucet should return 10000*2^64, instead it returns 0

**Comment by joeykrug** [comment]
Edit: works now w/ the latest version of serpent --- closing issue
